linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - depguard
    - gci
    - bodyclose
    - errname
    - errorlint
    - copyloopvar
    - gochecknoinits
    - gochecknoglobals
    - err113
    - gocyclo
    - nestif
    - nlreturn
    - nolintlint
    - prealloc
    - revive
    - unused
    - wastedassign
    - wsl
    - rowserrcheck
    - sqlclosecheck

linters-settings:
  errcheck:
    exclude-functions:
      - go.wamod.dev/warning.Warnf
      - go.wamod.dev/warning.Warn
  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - go.wamod.dev/warning
  gci:
    sections:
      - Standard
      - Default
      - Prefix(go.wamod.dev/warning)
