# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^fix(ci):"
      - "^chore:"
      - "^docs:"


release:
  prerelease: auto
